version: 2

node_6: &node_6
  docker:
    - image: node:6@sha256:6ed17656f6b15e5d97c2a7a6b73b76a237dffb6e0c0ccc78b52f98c5083889e3

node_8: &node_8
  docker:
    - image: node:8@sha256:f10c8218e3f92b513af9120f5eda5fed35b651343f940881d696b958cc16ab43

package_manager: &package_manager
  steps:
    - checkout
    - run: |
        echo "Required until 'npm' 5.2 is the oldest version used by a Node container."
        currentDirectory=$(pwd)
        mkdir -p /tmp/npm-install-directory
        cd /tmp/npm-install-directory
        npm install npm@latest --no-save
        rm -rf /usr/local/lib/node_modules
        mv node_modules /usr/local/lib/
        cd $currentDirectory
    - run: |
        echo "Required because Circle CI changes directory permissions to 777, and 'npm' won't install in that environment."
        npm install --unsafe-perm
    - save_cache:
        paths:
          - node_modules
          - ${HOME}/.npm
        key: dependencies
    - run: npm test && ($(npm bin)/codecov || echo "Codecov did not collect coverage reports")

jobs:
  node_6_job:
    <<: [*node_6, *package_manager]
  node_8_job:
    <<: [*node_8, *package_manager]

workflows:
  version: 2
  build:
    jobs:
      - node_6_job
      - node_8_job

notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/5b220f6576f228656526
